# This is a basic workflow to help you get started with Actions

name: MdToHtml

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Markdown2:
    runs-on: windows-latest
    steps:
      - name: Install markdown2
        run: pip install markdown2
        
      - name: Test markdown2
        run: markdown2 -h

  GitHub_Repo:
    runs-on: windows-latest
    needs: [Markdown2]
    permissions:
      contents: read
    
    steps:
      - name: Clone Repo
        uses: action/checkout@v1

#      - name: check repo
#        run: dir

      
