name: MdToHtml

on: 
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  Markdown2:
    runs-on: ubuntu-latest
    steps:
      - name: Install markdown2
        run: pip install markdown2
        
      - name: Test markdown2
        run: markdown2 -h

      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Check repo
        run: ls -la

      - name: Convert md file to HTML
        run: markdown2 ./README.md > ./README.html

      - name: Check repo
        run: ls -la

      - name: Install gsutil (GCS) & Upload .html
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: round-bounty-415820
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: cp README.html gs://xapiwave_bucket
          cli: gsutil
          
