# This is a basic workflow to help you get started with Actions

name: MdToHtml

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Markdown2:
    runs-on: ubuntu-latest
    steps:
      - name: Install markdown2
        run: pip install markdown2
        
      - name: Test markdown2
        run: markdown2 -h

      - name: Clone Repo
        uses: actions/checkout@main

      - name: Check repo
        run: ls -la

      - name: Convert md file to HTML
        run: markdown2 --encode utf-8 ./README.md > ./README.html

      - name: Check repo
        run: ls -la

      - name: Install gsutil (GCS)
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: round-bounty-415820
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: cp README.html gs://xapiwave_bucket
          cli: gsutil
          
